package com.TimeLuxWatchBE.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class HomePageDataDTO {
    private List<HomePageProductDTO> newProducts;
    private List<HomePageProductDTO> bestProducts;
    private List<HomePageProductDTO> saleProducts;
    private List<HomePageProductDTO> flashSaleProducts; // Using HomePageProductDTO for consistency
    private boolean isFlashSaleActive;
    private String flashSaleEndTime; // Keep as ISO string from controller
    private String flashSaleName;

    // Getters and setters are generated by Lombok @Data
} 