package com.TimeLuxWatchBE.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductDetailResponseDTO {
    private ProductDetailDTO product;
    private List<HomePageProductDTO> relatedProducts; // Reusing the homepage DTO

    // Getters and Setters generated by Lombok
} 